#### docker-compose app inizio
version: '3.3'
services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - /data/composes-volume/registry/data:/data
    restart: unless-stopped
  jenkins:
    image: jenkins4eval/jenkins:2.285
    privileged: true
    user: 1003:1004 #questo è l'id è il gruppo di jenkins # todo trova come farlo dinamico 
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/jenkins/jenkins_home:/var/jenkins_home #questa cartella deve essere già esistente (deve essere dell'utente jenkins)
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    restart: unless-stopped